/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        display: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        mono: ['SF Mono', 'JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'display-3xl': ['6rem', { lineHeight: '0.95', letterSpacing: '-0.055em', fontWeight: '800' }],
        'display-2xl': ['4.5rem', { lineHeight: '0.98', letterSpacing: '-0.05em', fontWeight: '800' }],
        'display-xl': ['3.75rem', { lineHeight: '1.0', letterSpacing: '-0.045em', fontWeight: '800' }],
        'display-lg': ['3rem', { lineHeight: '1.05', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-md': ['2.25rem', { lineHeight: '1.1', letterSpacing: '-0.035em', fontWeight: '700' }],
        'display-sm': ['1.75rem', { lineHeight: '1.15', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-xs': ['1.375rem', { lineHeight: '1.2', letterSpacing: '-0.025em', fontWeight: '600' }],
      },
      colors: {
        semantic: {
          bg: 'var(--color-bg)',
          surface: 'var(--color-surface)',
          'surface-elevated': 'var(--color-surface-elevated)',
          'surface-muted': 'var(--color-surface-muted)',
          'surface-hover': 'var(--color-surface-hover)',
          'surface-active': 'var(--color-surface-active)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          inverse: 'var(--color-text-inverse)',
          link: 'var(--color-text-link)',
          'link-hover': 'var(--color-text-link-hover)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          strong: 'var(--color-border-strong)',
          hover: 'var(--color-border-hover)',
          subtle: 'var(--color-border-subtle)',
          focus: 'var(--color-border-focus)',
          accent: 'var(--color-border-accent)',
          danger: 'var(--color-border-danger)',
          success: 'var(--color-border-success)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          hover: 'var(--accent-hover)',
          active: 'var(--accent-active)',
          subtle: 'var(--accent-subtle)',
          'subtle-hover': 'var(--accent-subtle-hover)',
          on: 'var(--accent-on)',
        },
        success: {
          DEFAULT: 'var(--success)',
          hover: 'var(--success-hover)',
          subtle: 'var(--success-subtle)',
          on: 'var(--success-on)',
        },
        danger: {
          DEFAULT: 'var(--danger)',
          hover: 'var(--danger-hover)',
          subtle: 'var(--danger-subtle)',
          on: 'var(--danger-on)',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          hover: 'var(--warning-hover)',
          subtle: 'var(--warning-subtle)',
          on: 'var(--warning-on)',
        },
        info: {
          DEFAULT: 'var(--info)',
          subtle: 'var(--info-subtle)',
          on: 'var(--info-on)',
        },
        chat: {
          bg: 'var(--chat-bg)',
          'bubble-a': 'var(--chat-bubble-a)',
          'bubble-b': 'var(--chat-bubble-b)',
          'bubble-border-a': 'var(--chat-bubble-border-a)',
          'bubble-border-b': 'var(--chat-bubble-border-b)',
          'bubble-text-a': 'var(--chat-bubble-text-a)',
          'bubble-text-b': 'var(--chat-bubble-text-b)',
          divider: 'var(--chat-divider)',
          timestamp: 'var(--chat-timestamp)',
          'system-bg': 'var(--chat-system-bg)',
          'system-text': 'var(--chat-system-text)',
        },
        overlay: 'var(--color-overlay)',
        scrim: 'var(--color-scrim)',
        vanish: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
          950: '#022c22',
        },
        surface: {
          DEFAULT: 'var(--color-bg)',
          light: 'var(--color-bg)',
          muted: 'var(--color-surface-muted)',
          card: 'var(--color-surface)',
          elevated: 'var(--color-surface-elevated)',
        },
      },
      boxShadow: {
        'xs': 'var(--shadow-xs)',
        'soft': 'var(--shadow-sm)',
        'elevated': 'var(--shadow-md)',
        'premium': 'var(--shadow-lg)',
        'premium-lg': 'var(--shadow-xl)',
        'premium-xl': 'var(--shadow-2xl)',
        'inner': 'var(--shadow-inner)',
        'bubble': 'var(--shadow-bubble)',
        'bubble-elevated': 'var(--shadow-bubble-elevated)',
        'focus': 'var(--focus-ring)',
        'glow': '0 0 20px var(--accent-subtle), 0 0 40px var(--accent-subtle)',
        'glow-lg': '0 0 30px var(--accent-subtle), 0 0 60px var(--accent-subtle), 0 0 90px var(--accent-subtle)',
      },
      animation: {
        'fade-in': 'fade-in 0.5s cubic-bezier(0.16,1,0.3,1) both',
        'fade-up': 'fade-up 0.7s cubic-bezier(0.16,1,0.3,1) both',
        'fade-down': 'fade-down 0.5s cubic-bezier(0.16,1,0.3,1) both',
        'scale-in': 'scale-in 0.45s cubic-bezier(0.16,1,0.3,1) both',
        'slide-up': 'slide-up 0.55s cubic-bezier(0.16,1,0.3,1) both',
        'slide-down': 'slide-down 0.4s cubic-bezier(0.16,1,0.3,1) both',
        'slide-up-sm': 'slide-up-sm 0.4s cubic-bezier(0.16,1,0.3,1) both',
        'message-in': 'message-in 0.4s cubic-bezier(0.16,1,0.3,1) both',
        'message-out': 'message-out 0.25s ease-in both',
        'drift': 'drift 20s ease-in-out infinite alternate',
        'drift-reverse': 'drift-reverse 25s ease-in-out infinite alternate',
        'pulse-soft': 'pulse-soft 3s ease-in-out infinite',
        'pulse-ring': 'pulse-ring 1.5s cubic-bezier(0.215,0.61,0.355,1) infinite',
        'float': 'float 7s ease-in-out infinite',
        'bounce-gentle': 'bounce-gentle 2s ease-in-out infinite',
        'skeleton': 'skeleton-shimmer 1.5s ease-in-out infinite',
        'scroll-reveal': 'scroll-reveal 0.8s cubic-bezier(0.16,1,0.3,1) both',
        'scroll-reveal-sm': 'scroll-reveal-sm 0.6s cubic-bezier(0.16,1,0.3,1) both',
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'morph': 'morph 8s ease-in-out infinite',
        'orbit': 'orbit 12s linear infinite',
        'ken-burns': 'ken-burns 20s ease-in-out infinite alternate',
        'typing-cursor': 'typing-cursor 1s step-end infinite',
        'gradient-shift': 'gradient-shift 6s ease infinite',
        'scale-pulse': 'scale-pulse 2s ease-in-out infinite',
        'slide-up-stagger': 'slide-up-stagger 0.6s cubic-bezier(0.16,1,0.3,1) both',
        'premium-appear': 'premium-appear 0.8s cubic-bezier(0.16,1,0.3,1) both',
        'progress-bar': 'progress-bar 60s linear forwards',
        'text-gradient': 'gradient-shift 4s ease infinite',
        'float-delayed': 'float-delayed 6s ease-in-out infinite',
        'ripple': 'ripple 0.6s ease-out',
        'spin-slow': 'spin 8s linear infinite',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'fade-up': { from: { opacity: '0', transform: 'translateY(20px) scale(0.98)' }, to: { opacity: '1', transform: 'translateY(0) scale(1)' } },
        'fade-down': { from: { opacity: '0', transform: 'translateY(-16px) scale(0.98)' }, to: { opacity: '1', transform: 'translateY(0) scale(1)' } },
        'scale-in': { from: { opacity: '0', transform: 'scale(0.9)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'slide-up': { from: { opacity: '0', transform: 'translateY(28px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-up-sm': { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-down': { from: { opacity: '0', transform: 'translateY(-24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'message-in': { from: { opacity: '0', transform: 'translateY(12px) scale(0.96)' }, to: { opacity: '1', transform: 'translateY(0) scale(1)' } },
        'message-out': { from: { opacity: '1', transform: 'scale(1)' }, to: { opacity: '0', transform: 'scale(0.92)' } },
        'drift': {
          '0%': { transform: 'translate(0, 0) scale(1)', opacity: '0.15' },
          '50%': { transform: 'translate(60px, -30px) scale(1.15)', opacity: '0.3' },
          '100%': { transform: 'translate(-30px, 40px) scale(0.95)', opacity: '0.15' },
        },
        'drift-reverse': {
          '0%': { transform: 'translate(0, 0) scale(1)', opacity: '0.12' },
          '50%': { transform: 'translate(-50px, 40px) scale(1.1)', opacity: '0.25' },
          '100%': { transform: 'translate(40px, -30px) scale(0.9)', opacity: '0.12' },
        },
        'pulse-soft': { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.5' } },
        'pulse-ring': {
          '0%': { transform: 'scale(0.8)', opacity: '1' },
          '100%': { transform: 'scale(2.2)', opacity: '0' },
        },
        'float': { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
        'float-delayed': {
          '0%,100%': { transform: 'translateY(0)' },
          '25%': { transform: 'translateY(-6px)' },
          '75%': { transform: 'translateY(-3px)' },
        },
        'bounce-gentle': {
          '0%,100%': { transform: 'translateY(0)' },
          '25%': { transform: 'translateY(-4px)' },
          '75%': { transform: 'translateY(-2px)' },
        },
        'skeleton-shimmer': {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        'scroll-reveal': {
          from: { opacity: '0', transform: 'translateY(30px) scale(0.97)' },
          to: { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'scroll-reveal-sm': {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'glow-pulse': {
          '0%,100%': { boxShadow: '0 0 20px var(--accent-subtle), 0 0 40px var(--accent-subtle)' },
          '50%': { boxShadow: '0 0 30px var(--accent-subtle), 0 0 60px var(--accent-subtle), 0 0 80px var(--accent-subtle)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        'morph': {
          '0%,100%': { borderRadius: '60% 40% 30% 70%/60% 30% 70% 40%' },
          '50%': { borderRadius: '30% 60% 70% 40%/50% 60% 30% 60%' },
        },
        'orbit': {
          from: { transform: 'rotate(0deg) translateX(8px) rotate(0deg)' },
          to: { transform: 'rotate(360deg) translateX(8px) rotate(-360deg)' },
        },
        'ken-burns': {
          '0%': { transform: 'scale(1) translate(0, 0)' },
          '100%': { transform: 'scale(1.08) translate(-10px, -5px)' },
        },
        'typing-cursor': {
          '0%,100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        'gradient-shift': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        'scale-pulse': {
          '0%,100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
        },
        'slide-up-stagger': {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'premium-appear': {
          from: { opacity: '0', transform: 'translateY(24px) scale(0.96)' },
          to: { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'progress-bar': {
          from: { transform: 'scaleX(1)' },
          to: { transform: 'scaleX(0)' },
        },
        'ripple': {
          from: { transform: 'scale(0)', opacity: '1' },
          to: { transform: 'scale(4)', opacity: '0' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-accent': 'var(--gradient-accent)',
        'gradient-surface': 'var(--gradient-surface)',
        'gradient-warm': 'linear-gradient(135deg, var(--accent-400), var(--accent-600), #2563eb)',
        'gradient-cool': 'linear-gradient(135deg, #2563eb, var(--accent-500), var(--accent-400))',
        'noise': `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='1'/%3E%3C/svg%3E")`,
      },
      backdropBlur: {
        xs: '4px',
        '3xl': '64px',
        '4xl': '80px',
      },
      borderRadius: {
        '2xl': '16px',
        '3xl': '20px',
        '4xl': '24px',
        '5xl': '32px',
        '6xl': '40px',
        '7xl': '48px',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.16,1,0.3,1)',
        'spring-snappy': 'cubic-bezier(0.22,1,0.36,1)',
        'spring-gentle': 'cubic-bezier(0.34,1.2,0.64,1)',
      },
      opacity: { '2': '0.02', '3': '0.03', '4': '0.04', '8': '0.08', '15': '0.15', '85': '0.85' },
      spacing: { '18': '4.5rem', '22': '5.5rem', '30': '7.5rem', '34': '8.5rem', '38': '9.5rem' },
    },
  },
  plugins: [],
}
